services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5431"
  app:
    build:
      context: cleanix/
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./cleanix:/cleanix
    env_file:
      - .env


volumes:
  pgdata:
    driver: local
