services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build:
      context: cleanix/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./cleanix:/cleanix
    env_file:
      - .env


volumes:
  pgdata:
    driver: local
